import javax.swing.*;
import javax.swing.border.*;
import java.awt.*;
import java.util.*;

public class Main {
    static final Color INK = new Color(28,36,48), PAPER = new Color(242,236,218), CARD = new Color(255,253,248), ACCENT = new Color(201,138,46), LINE = new Color(217,206,175), GREEN = new Color(76,122,85), ORANGE = new Color(193,101,47), GREY = new Color(110,101,88);
    static final String[] WORDS = {"CRANE","SLATE","PLANT","BRAVE","CHAIR","HOUSE","WATER","LIGHT","MUSIC","PIZZA","TIGER","APPLE","BEACH","DREAM","GRAPE","SMILE","STONE","TRAIN","WORLD","YOUTH"};
    static final Map<String,String> users = new HashMap<>();
    static final Map<String,Integer> plays = new HashMap<>();
    static final java.util.List<String> reports = new ArrayList<>();
    static JFrame frame; static String currentUser=""; static boolean admin=false;
    static { users.put("Admin", "Admin$123"); }

    public static void main(String[] args) { SwingUtilities.invokeLater(() -> { frame = new JFrame("Word Guess"); frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); frame.setSize(650,700); frame.setMinimumSize(new Dimension(540,600)); frame.setLocationRelativeTo(null); loginPage(); frame.setVisible(true); }); }
    static JPanel page(String title) {
        JPanel root = new JPanel(new BorderLayout()); root.setBackground(PAPER);
        JPanel header = new JPanel(new BorderLayout()); header.setBackground(INK); header.setBorder(new EmptyBorder(18,25,18,25));
        JLabel brand = new JLabel("WORD GUESS"); brand.setForeground(PAPER); brand.setFont(new Font("Serif",Font.BOLD,25)); header.add(brand,BorderLayout.WEST);
        if (!currentUser.isEmpty()) { JLabel who = new JLabel(currentUser + (admin?"  ·  ADMIN":"  ·  PLAYER") + "     "); who.setForeground(new Color(199,204,214)); header.add(who,BorderLayout.CENTER); JButton logout=button("Log out",false); logout.addActionListener(e->{currentUser="";admin=false;loginPage();}); header.add(logout,BorderLayout.EAST); }
        root.add(header,BorderLayout.NORTH); JPanel center=new JPanel(new GridBagLayout()); center.setOpaque(false); JPanel card=new JPanel(); card.setLayout(new BoxLayout(card,BoxLayout.Y_AXIS)); card.setBackground(CARD); card.setBorder(new CompoundBorder(new DashedBorder(LINE),new EmptyBorder(26,30,26,30))); card.setPreferredSize(new Dimension(440, title.equals("Word Guess")?510:390));
        JLabel heading=new JLabel(title); heading.setFont(new Font("Serif",Font.BOLD,25)); heading.setForeground(INK); heading.setAlignmentX(Component.LEFT_ALIGNMENT); card.add(heading); card.add(Box.createVerticalStrut(22)); center.add(card); root.add(center,BorderLayout.CENTER); frame.setContentPane(root); frame.revalidate(); frame.repaint(); return card;
    }
    static class DashedBorder extends LineBorder { DashedBorder(Color c){super(c,2,true);} public void paintBorder(Component c,Graphics g,int x,int y,int w,int h){ Graphics2D g2=(Graphics2D)g.create(); g2.setColor(lineColor); g2.setStroke(new BasicStroke(1.5f,BasicStroke.CAP_BUTT,BasicStroke.JOIN_ROUND,1,new float[]{5,4},0)); g2.drawRoundRect(x+1,y+1,w-3,h-3,3,3);g2.dispose();}}
    static JButton button(String text, boolean primary){ JButton b=new JButton(text); b.setFont(new Font("SansSerif",Font.BOLD,14)); b.setFocusPainted(false); b.setBackground(primary?ACCENT:INK); b.setForeground(Color.WHITE); b.setBorder(new EmptyBorder(10,16,10,16)); b.setAlignmentX(Component.LEFT_ALIGNMENT); return b; }
    static JTextField field(String hint){ JTextField f=new JTextField(); f.setMaximumSize(new Dimension(Integer.MAX_VALUE,38)); f.setFont(new Font("SansSerif",Font.PLAIN,15)); f.setBorder(new CompoundBorder(new LineBorder(LINE,1),new EmptyBorder(8,10,8,10))); f.putClientProperty("hint",hint); return f; }
    static void loginPage(){ JPanel c=page("Log in"); JTextField u=field("Username"); JPasswordField p=new JPasswordField(); p.setMaximumSize(new Dimension(Integer.MAX_VALUE,38)); p.setBorder(new CompoundBorder(new LineBorder(LINE,1),new EmptyBorder(8,10,8,10))); addLabel(c,"Username");c.add(u);c.add(Box.createVerticalStrut(12));addLabel(c,"Password");c.add(p);c.add(Box.createVerticalStrut(18)); JButton go=button("Log in",true); c.add(go); JLabel msg=note("New here? Register a player account below."); c.add(Box.createVerticalStrut(16));c.add(msg); JButton reg=button("Create account",false);c.add(Box.createVerticalStrut(8));c.add(reg);
        go.addActionListener(e->{String name=u.getText().trim(),pass=new String(p.getPassword()); if(users.containsKey(name)&&users.get(name).equals(pass)){currentUser=name;admin=name.equals("Admin");if(admin)adminPage();else gamePage();}else msg.setText("Invalid username or password.");}); reg.addActionListener(e->registerPage()); }
    static void registerPage(){ JPanel c=page("Create account"); JTextField u=field("Username");JPasswordField p=new JPasswordField();p.setMaximumSize(new Dimension(Integer.MAX_VALUE,38));p.setBorder(new CompoundBorder(new LineBorder(LINE,1),new EmptyBorder(8,10,8,10)));addLabel(c,"Username (5+ letters)");c.add(u);c.add(Box.createVerticalStrut(12));addLabel(c,"Password (letter, number and $ % * ) )");c.add(p);c.add(Box.createVerticalStrut(18));JLabel msg=note("Choose a username with at least 5 letters.");c.add(msg);c.add(Box.createVerticalStrut(12));JButton create=button("Register",true);c.add(create);JButton back=button("Back to login",false);c.add(Box.createVerticalStrut(8));c.add(back);create.addActionListener(e->{String name=u.getText().trim(),pass=new String(p.getPassword());if(!name.matches("[A-Za-z]{5,}"))msg.setText("Username must be at least 5 letters (A-Z only).");else if(pass.length()<5||!pass.matches(".*[A-Za-z].*")||!pass.matches(".*[0-9].*")||!pass.matches(".*[$%*)].*"))msg.setText("Password needs 5+ chars, a letter, digit and $ % * or ).");else if(users.containsKey(name))msg.setText("Username already taken.");else{users.put(name,pass);msg.setText("Registered! You can now log in.");}});back.addActionListener(e->loginPage()); }
    static void gamePage(){ JPanel c=page("Word Guess");int used=plays.getOrDefault(currentUser,0);JLabel status=note("Words played today: "+used+" / 3");c.add(status);c.add(Box.createVerticalStrut(12));JPanel board=new JPanel(new GridLayout(5,5,7,7));board.setOpaque(false);JLabel[][] cells=new JLabel[5][5];for(int r=0;r<5;r++)for(int col=0;col<5;col++){JLabel l=new JLabel(" ",SwingConstants.CENTER);l.setOpaque(true);l.setBackground(Color.WHITE);l.setForeground(Color.WHITE);l.setBorder(new LineBorder(LINE,2));l.setFont(new Font(Font.MONOSPACED,Font.BOLD,22));cells[r][col]=l;board.add(l);}board.setMaximumSize(new Dimension(310,310));board.setAlignmentX(Component.CENTER_ALIGNMENT);c.add(board);c.add(Box.createVerticalStrut(16));JTextField guess=field("Enter 5-letter word");guess.setMaximumSize(new Dimension(Integer.MAX_VALUE,40));c.add(guess);c.add(Box.createVerticalStrut(10));JLabel msg=note("Guess the hidden five-letter word in five tries.");c.add(msg);c.add(Box.createVerticalStrut(10));JButton submit=button("Submit guess",true);c.add(submit);c.add(Box.createVerticalStrut(8));JButton newGame=button("Start new word",false);c.add(newGame); final String[] answer={WORDS[new Random().nextInt(WORDS.length)]};final int[] row={0}; final boolean[] done={false};
        Runnable start=()->{if(plays.getOrDefault(currentUser,0)>=3){msg.setText("Daily limit reached. Come back tomorrow!");return;}answer[0]=WORDS[new Random().nextInt(WORDS.length)];row[0]=0;done[0]=false;for(JLabel[] rr:cells)for(JLabel l:rr){l.setText(" ");l.setBackground(Color.WHITE);l.setForeground(INK);l.setBorder(new LineBorder(LINE,2));}plays.put(currentUser,plays.getOrDefault(currentUser,0)+1);status.setText("Words played today: "+plays.get(currentUser)+" / 3");msg.setText("Guess the hidden five-letter word in five tries.");guess.setText("");submit.setEnabled(true);};
        submit.addActionListener(e->{if(done[0])return;String g=guess.getText().trim().toUpperCase(Locale.ROOT);if(!g.matches("[A-Z]{5}")){msg.setText("Enter exactly five letters (A-Z).");return;}if(row[0]>=5)return;for(int i=0;i<5;i++){cells[row[0]][i].setText(g.substring(i,i+1));Color color=GREY;if(g.charAt(i)==answer[0].charAt(i))color=GREEN;else if(answer[0].indexOf(g.charAt(i))>=0)color=ORANGE;cells[row[0]][i].setBackground(color);}row[0]++;guess.setText("");if(g.equals(answer[0])){msg.setText("Correct! The word was "+answer[0]+".");done[0]=true;submit.setEnabled(false);reports.add(currentUser+" — WON — "+answer[0]);}else if(row[0]==5){msg.setText("Better luck next time! Word: "+answer[0]);done[0]=true;submit.setEnabled(false);reports.add(currentUser+" — LOST — "+answer[0]);}else msg.setText("Try again! Attempts remaining: "+(5-row[0]));});newGame.addActionListener(e->start.run()); }
    static void adminPage(){JPanel c=page("Daily report");c.add(note("Player activity recorded during this session"));c.add(Box.createVerticalStrut(15));JTextArea area=new JTextArea(15,30);area.setEditable(false);area.setFont(new Font("Monospaced",Font.PLAIN,14));area.setBackground(Color.WHITE);area.setBorder(new EmptyBorder(10,10,10,10));refreshReports(area);JScrollPane scroll=new JScrollPane(area);scroll.setAlignmentX(Component.LEFT_ALIGNMENT);c.add(scroll);c.add(Box.createVerticalStrut(12));JButton refresh=button("Refresh report",true);c.add(refresh);refresh.addActionListener(e->refreshReports(area)); }
    static void refreshReports(JTextArea a){if(reports.isEmpty())a.setText("No games played in this session yet.");else{StringBuilder b=new StringBuilder("PLAYER GAME RESULT\n------------------------------\n");for(String r:reports)b.append(r).append('\n');a.setText(b.toString());}}
    static void addLabel(JPanel p,String s){JLabel l=new JLabel(s);l.setForeground(new Color(58,68,83));l.setFont(new Font("SansSerif",Font.PLAIN,13));l.setAlignmentX(Component.LEFT_ALIGNMENT);p.add(l);p.add(Box.createVerticalStrut(5));}
    static JLabel note(String s){JLabel l=new JLabel(s);l.setForeground(new Color(58,68,83));l.setFont(new Font("SansSerif",Font.PLAIN,13));l.setAlignmentX(Component.LEFT_ALIGNMENT);return l;}
}
